#!/usr/bin/env bash

# Check if the PID file exists
if [ -f /var/run/my_process.pid ]
then
    PID=$(cat /var/run/my_process.pid)
    # Check if the process is running
    if ps -p $PID > /dev/null
    then
        echo "manage_my_process is already running"
        exit 1
    else
        echo "Removing old PID file"
        rm /var/run/my_process.pid
    fi
fi

case $1 in
    start)
        echo "Starting manage_my_process"
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        ;;
    stop)
        echo "Stopping manage_my_process"
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]
        then
            echo "Restarting manage_my_process"
            kill $(cat /var/run/my_process.pid)
        fi
        echo "Starting manage_my_process"
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
